// <auto-generated/>
#pragma warning disable CS0618
using DataHandler.NhlApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\skater-stats-leaders\current
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurrentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/skater-stats-leaders/current{?categories*,limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/skater-stats-leaders/current{?categories*,limit*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve current skater stats leaders.
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.StatLeaderResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DataHandler.NhlApiClient.Models.Error">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DataHandler.NhlApiClient.Models.StatLeaderResponse?> GetAsync(Action<RequestConfiguration<global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder.CurrentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DataHandler.NhlApiClient.Models.StatLeaderResponse> GetAsync(Action<RequestConfiguration<global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder.CurrentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::DataHandler.NhlApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DataHandler.NhlApiClient.Models.StatLeaderResponse>(requestInfo, global::DataHandler.NhlApiClient.Models.StatLeaderResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve current skater stats leaders.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder.CurrentRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder.CurrentRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve current skater stats leaders.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CurrentRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("categories")]
            public string? Categories { get; set; }
#nullable restore
#else
            [QueryParameter("categories")]
            public string Categories { get; set; }
#endif
            [QueryParameter("limit")]
            public double? Limit { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CurrentRequestBuilderGetRequestConfiguration : RequestConfiguration<global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder.CurrentRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
