// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Schedule
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetExpandQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "schedule.brodcasts")]
        #pragma warning disable CS1591
        ScheduleBrodcasts,
        #pragma warning restore CS1591
        [EnumMember(Value = "schedule.linescore")]
        #pragma warning disable CS1591
        ScheduleLinescore,
        #pragma warning restore CS1591
        [EnumMember(Value = "schedule.ticket")]
        #pragma warning disable CS1591
        ScheduleTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "team.schedule.previous")]
        #pragma warning disable CS1591
        TeamSchedulePrevious,
        #pragma warning restore CS1591
    }
}
