// <auto-generated/>
#pragma warning disable CS0618
using DataHandler.NhlApiClient.Game.Item.Feed.Live;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DataHandler.NhlApiClient.Game.Item.Feed
{
    /// <summary>
    /// Builds and executes requests for operations under \game\{id}\feed
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FeedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The live property</summary>
        public global::DataHandler.NhlApiClient.Game.Item.Feed.Live.LiveRequestBuilder Live
        {
            get => new global::DataHandler.NhlApiClient.Game.Item.Feed.Live.LiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Game.Item.Feed.FeedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game/{id}/feed", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Game.Item.Feed.FeedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game/{id}/feed", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
