// <auto-generated/>
#pragma warning disable CS0618
using DataHandler.NhlApiClient.People.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DataHandler.NhlApiClient.People
{
    /// <summary>
    /// Builds and executes requests for operations under \people
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PeopleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the DataHandler.NhlApiClient.people.item collection</summary>
        /// <param name="position">The ID of the player.</param>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.People.Item.PeopleItemRequestBuilder"/></returns>
        public global::DataHandler.NhlApiClient.People.Item.PeopleItemRequestBuilder this[double position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::DataHandler.NhlApiClient.People.Item.PeopleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the DataHandler.NhlApiClient.people.item collection</summary>
        /// <param name="position">The ID of the player.</param>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.People.Item.PeopleItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::DataHandler.NhlApiClient.People.Item.PeopleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::DataHandler.NhlApiClient.People.Item.PeopleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.People.PeopleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PeopleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/people", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.People.PeopleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PeopleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/people", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
