// <auto-generated/>
#pragma warning disable CS0618
using DataHandler.NhlApiClient.Game.Item.Boxscore;
using DataHandler.NhlApiClient.Game.Item.Content;
using DataHandler.NhlApiClient.Game.Item.Feed;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DataHandler.NhlApiClient.Game.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \game\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The boxscore property</summary>
        public global::DataHandler.NhlApiClient.Game.Item.Boxscore.BoxscoreRequestBuilder Boxscore
        {
            get => new global::DataHandler.NhlApiClient.Game.Item.Boxscore.BoxscoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The content property</summary>
        public global::DataHandler.NhlApiClient.Game.Item.Content.ContentRequestBuilder Content
        {
            get => new global::DataHandler.NhlApiClient.Game.Item.Content.ContentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The feed property</summary>
        public global::DataHandler.NhlApiClient.Game.Item.Feed.FeedRequestBuilder Feed
        {
            get => new global::DataHandler.NhlApiClient.Game.Item.Feed.FeedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Game.Item.GameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Game.Item.GameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
