// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Teams
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetExpandQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "team.roster")]
        #pragma warning disable CS1591
        TeamRoster,
        #pragma warning restore CS1591
        [EnumMember(Value = "team.schedule.next")]
        #pragma warning disable CS1591
        TeamScheduleNext,
        #pragma warning restore CS1591
        [EnumMember(Value = "team.schedule.previous")]
        #pragma warning disable CS1591
        TeamSchedulePrevious,
        #pragma warning restore CS1591
    }
}
