// <auto-generated/>
#pragma warning disable CS0618
using DataHandler.NhlApiClient.V1.Network.TvSchedule;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DataHandler.NhlApiClient.V1.Network
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\network
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NetworkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The tvSchedule property</summary>
        public global::DataHandler.NhlApiClient.V1.Network.TvSchedule.TvScheduleRequestBuilder TvSchedule
        {
            get => new global::DataHandler.NhlApiClient.V1.Network.TvSchedule.TvScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.Network.NetworkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetworkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/network", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.Network.NetworkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetworkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/network", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
