// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Conference_shortName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "East")]
        #pragma warning disable CS1591
        East,
        #pragma warning restore CS1591
        [EnumMember(Value = "West")]
        #pragma warning disable CS1591
        West,
        #pragma warning restore CS1591
        [EnumMember(Value = "WCup")]
        #pragma warning disable CS1591
        WCup,
        #pragma warning restore CS1591
    }
}
