// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Conference_abbreviation
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "E")]
        #pragma warning disable CS1591
        E,
        #pragma warning restore CS1591
        [EnumMember(Value = "W")]
        #pragma warning disable CS1591
        W,
        #pragma warning restore CS1591
        [EnumMember(Value = "WCH")]
        #pragma warning disable CS1591
        WCH,
        #pragma warning restore CS1591
    }
}
