// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Conference_name
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Eastern")]
        #pragma warning disable CS1591
        Eastern,
        #pragma warning restore CS1591
        [EnumMember(Value = "Western")]
        #pragma warning disable CS1591
        Western,
        #pragma warning restore CS1591
        [EnumMember(Value = "World Cup of Hockey")]
        #pragma warning disable CS1591
        WorldCupOfHockey,
        #pragma warning restore CS1591
    }
}
