// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Draft_drafts_rounds_picks : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The pickInRound property</summary>
        public double? PickInRound { get; set; }
        /// <summary>The pickOverall property</summary>
        public double? PickOverall { get; set; }
        /// <summary>The prospect property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_prospect? Prospect { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_prospect Prospect { get; set; }
#endif
        /// <summary>The round property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Round { get; set; }
#nullable restore
#else
        public string Round { get; set; }
#endif
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_team? Team { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_team Team { get; set; }
#endif
        /// <summary>The year property</summary>
        public double? Year { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks"/> and sets the default values.
        /// </summary>
        public Draft_drafts_rounds_picks()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pickInRound", n => { PickInRound = n.GetDoubleValue(); } },
                { "pickOverall", n => { PickOverall = n.GetDoubleValue(); } },
                { "prospect", n => { Prospect = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_prospect>(global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_prospect.CreateFromDiscriminatorValue); } },
                { "round", n => { Round = n.GetStringValue(); } },
                { "team", n => { Team = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_team>(global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_team.CreateFromDiscriminatorValue); } },
                { "year", n => { Year = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("pickInRound", PickInRound);
            writer.WriteDoubleValue("pickOverall", PickOverall);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_prospect>("prospect", Prospect);
            writer.WriteStringValue("round", Round);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks_team>("team", Team);
            writer.WriteDoubleValue("year", Year);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
