// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Draft_drafts_rounds : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The picks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks>? Picks { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks> Picks { get; set; }
#endif
        /// <summary>The round property</summary>
        public double? Round { get; set; }
        /// <summary>The roundNumber property</summary>
        public double? RoundNumber { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds"/> and sets the default values.
        /// </summary>
        public Draft_drafts_rounds()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "picks", n => { Picks = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks>(global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks.CreateFromDiscriminatorValue)?.AsList(); } },
                { "round", n => { Round = n.GetDoubleValue(); } },
                { "roundNumber", n => { RoundNumber = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Draft_drafts_rounds_picks>("picks", Picks);
            writer.WriteDoubleValue("round", Round);
            writer.WriteDoubleValue("roundNumber", RoundNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
