// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GameContent_media_milestones : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.GameContent_media_milestones_items>? Items { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.GameContent_media_milestones_items> Items { get; set; }
#endif
        /// <summary>The streamStart property</summary>
        public DateTimeOffset? StreamStart { get; set; }
        /// <summary>The title property</summary>
        public global::DataHandler.NhlApiClient.Models.GameContent_media_milestones_title? Title { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.GameContent_media_milestones"/> and sets the default values.
        /// </summary>
        public GameContent_media_milestones()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.GameContent_media_milestones"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.GameContent_media_milestones CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.GameContent_media_milestones();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.GameContent_media_milestones_items>(global::DataHandler.NhlApiClient.Models.GameContent_media_milestones_items.CreateFromDiscriminatorValue)?.AsList(); } },
                { "streamStart", n => { StreamStart = n.GetDateTimeOffsetValue(); } },
                { "title", n => { Title = n.GetEnumValue<global::DataHandler.NhlApiClient.Models.GameContent_media_milestones_title>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.GameContent_media_milestones_items>("items", Items);
            writer.WriteDateTimeOffsetValue("streamStart", StreamStart);
            writer.WriteEnumValue<global::DataHandler.NhlApiClient.Models.GameContent_media_milestones_title>("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
