// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GameContent_media_milestones_title
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Milestones")]
        #pragma warning disable CS1591
        Milestones,
        #pragma warning restore CS1591
    }
}
