// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Game_liveData_plays : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allPlays property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.GamePlay>? AllPlays { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.GamePlay> AllPlays { get; set; }
#endif
        /// <summary>The currentPlay property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.GamePlay? CurrentPlay { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.GamePlay CurrentPlay { get; set; }
#endif
        /// <summary>The penaltyPlays property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? PenaltyPlays { get; set; }
#nullable restore
#else
        public List<double?> PenaltyPlays { get; set; }
#endif
        /// <summary>The playsByPeriod property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.Game_liveData_plays_playsByPeriod>? PlaysByPeriod { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.Game_liveData_plays_playsByPeriod> PlaysByPeriod { get; set; }
#endif
        /// <summary>The scoringPlays property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? ScoringPlays { get; set; }
#nullable restore
#else
        public List<double?> ScoringPlays { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.Game_liveData_plays"/> and sets the default values.
        /// </summary>
        public Game_liveData_plays()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.Game_liveData_plays"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.Game_liveData_plays CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.Game_liveData_plays();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allPlays", n => { AllPlays = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.GamePlay>(global::DataHandler.NhlApiClient.Models.GamePlay.CreateFromDiscriminatorValue)?.AsList(); } },
                { "currentPlay", n => { CurrentPlay = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.GamePlay>(global::DataHandler.NhlApiClient.Models.GamePlay.CreateFromDiscriminatorValue); } },
                { "penaltyPlays", n => { PenaltyPlays = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "playsByPeriod", n => { PlaysByPeriod = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Game_liveData_plays_playsByPeriod>(global::DataHandler.NhlApiClient.Models.Game_liveData_plays_playsByPeriod.CreateFromDiscriminatorValue)?.AsList(); } },
                { "scoringPlays", n => { ScoringPlays = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.GamePlay>("allPlays", AllPlays);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.GamePlay>("currentPlay", CurrentPlay);
            writer.WriteCollectionOfPrimitiveValues<double?>("penaltyPlays", PenaltyPlays);
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Game_liveData_plays_playsByPeriod>("playsByPeriod", PlaysByPeriod);
            writer.WriteCollectionOfPrimitiveValues<double?>("scoringPlays", ScoringPlays);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
