// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Game : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The copyright property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Copyright { get; set; }
#nullable restore
#else
        public string Copyright { get; set; }
#endif
        /// <summary>The gameData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Game_gameData? GameData { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Game_gameData GameData { get; set; }
#endif
        /// <summary>The gamePk property</summary>
        public double? GamePk { get; set; }
        /// <summary>The link property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Link { get; set; }
#nullable restore
#else
        public string Link { get; set; }
#endif
        /// <summary>The liveData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Game_liveData? LiveData { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Game_liveData LiveData { get; set; }
#endif
        /// <summary>The metaData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Game_metaData? MetaData { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Game_metaData MetaData { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.Game"/> and sets the default values.
        /// </summary>
        public Game()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.Game"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.Game CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.Game();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "copyright", n => { Copyright = n.GetStringValue(); } },
                { "gameData", n => { GameData = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Game_gameData>(global::DataHandler.NhlApiClient.Models.Game_gameData.CreateFromDiscriminatorValue); } },
                { "gamePk", n => { GamePk = n.GetDoubleValue(); } },
                { "link", n => { Link = n.GetStringValue(); } },
                { "liveData", n => { LiveData = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Game_liveData>(global::DataHandler.NhlApiClient.Models.Game_liveData.CreateFromDiscriminatorValue); } },
                { "metaData", n => { MetaData = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Game_metaData>(global::DataHandler.NhlApiClient.Models.Game_metaData.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("copyright", Copyright);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Game_gameData>("gameData", GameData);
            writer.WriteDoubleValue("gamePk", GamePk);
            writer.WriteStringValue("link", Link);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Game_liveData>("liveData", LiveData);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Game_metaData>("metaData", MetaData);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
