// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GameStats : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assists property</summary>
        public int? Assists { get; set; }
        /// <summary>The gameDate property</summary>
        public Date? GameDate { get; set; }
        /// <summary>The gameWinningGoals property</summary>
        public int? GameWinningGoals { get; set; }
        /// <summary>The goals property</summary>
        public int? Goals { get; set; }
        /// <summary>The homeRoadFlag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomeRoadFlag { get; set; }
#nullable restore
#else
        public string HomeRoadFlag { get; set; }
#endif
        /// <summary>The opponentAbbrev property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpponentAbbrev { get; set; }
#nullable restore
#else
        public string OpponentAbbrev { get; set; }
#endif
        /// <summary>The otGoals property</summary>
        public int? OtGoals { get; set; }
        /// <summary>The pim property</summary>
        public int? Pim { get; set; }
        /// <summary>The plusMinus property</summary>
        public int? PlusMinus { get; set; }
        /// <summary>The points property</summary>
        public int? Points { get; set; }
        /// <summary>The powerPlayGoals property</summary>
        public int? PowerPlayGoals { get; set; }
        /// <summary>The shifts property</summary>
        public int? Shifts { get; set; }
        /// <summary>The shootingPctg property</summary>
        public float? ShootingPctg { get; set; }
        /// <summary>The shorthandedGoals property</summary>
        public int? ShorthandedGoals { get; set; }
        /// <summary>The shots property</summary>
        public int? Shots { get; set; }
        /// <summary>The teamAbbrev property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamAbbrev { get; set; }
#nullable restore
#else
        public string TeamAbbrev { get; set; }
#endif
        /// <summary>The toi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Toi { get; set; }
#nullable restore
#else
        public string Toi { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.GameStats"/> and sets the default values.
        /// </summary>
        public GameStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.GameStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.GameStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.GameStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assists", n => { Assists = n.GetIntValue(); } },
                { "gameDate", n => { GameDate = n.GetDateValue(); } },
                { "gameWinningGoals", n => { GameWinningGoals = n.GetIntValue(); } },
                { "goals", n => { Goals = n.GetIntValue(); } },
                { "homeRoadFlag", n => { HomeRoadFlag = n.GetStringValue(); } },
                { "opponentAbbrev", n => { OpponentAbbrev = n.GetStringValue(); } },
                { "otGoals", n => { OtGoals = n.GetIntValue(); } },
                { "pim", n => { Pim = n.GetIntValue(); } },
                { "plusMinus", n => { PlusMinus = n.GetIntValue(); } },
                { "points", n => { Points = n.GetIntValue(); } },
                { "powerPlayGoals", n => { PowerPlayGoals = n.GetIntValue(); } },
                { "shifts", n => { Shifts = n.GetIntValue(); } },
                { "shootingPctg", n => { ShootingPctg = n.GetFloatValue(); } },
                { "shorthandedGoals", n => { ShorthandedGoals = n.GetIntValue(); } },
                { "shots", n => { Shots = n.GetIntValue(); } },
                { "teamAbbrev", n => { TeamAbbrev = n.GetStringValue(); } },
                { "toi", n => { Toi = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("assists", Assists);
            writer.WriteDateValue("gameDate", GameDate);
            writer.WriteIntValue("gameWinningGoals", GameWinningGoals);
            writer.WriteIntValue("goals", Goals);
            writer.WriteStringValue("homeRoadFlag", HomeRoadFlag);
            writer.WriteStringValue("opponentAbbrev", OpponentAbbrev);
            writer.WriteIntValue("otGoals", OtGoals);
            writer.WriteIntValue("pim", Pim);
            writer.WriteIntValue("plusMinus", PlusMinus);
            writer.WriteIntValue("points", Points);
            writer.WriteIntValue("powerPlayGoals", PowerPlayGoals);
            writer.WriteIntValue("shifts", Shifts);
            writer.WriteFloatValue("shootingPctg", ShootingPctg);
            writer.WriteIntValue("shorthandedGoals", ShorthandedGoals);
            writer.WriteIntValue("shots", Shots);
            writer.WriteStringValue("teamAbbrev", TeamAbbrev);
            writer.WriteStringValue("toi", Toi);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
