// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GameContent_media_milestones_items_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BROADCAST_START")]
        #pragma warning disable CS1591
        BROADCAST_START,
        #pragma warning restore CS1591
        [EnumMember(Value = "BROADCAST_END")]
        #pragma warning disable CS1591
        BROADCAST_END,
        #pragma warning restore CS1591
        [EnumMember(Value = "GOAL")]
        #pragma warning disable CS1591
        GOAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERIOD_END")]
        #pragma warning disable CS1591
        PERIOD_END,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERIOD_START")]
        #pragma warning disable CS1591
        PERIOD_START,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHOT")]
        #pragma warning disable CS1591
        SHOT,
        #pragma warning restore CS1591
    }
}
