// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Game_gameData_status : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The abstractGameState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AbstractGameState { get; set; }
#nullable restore
#else
        public string AbstractGameState { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The codedGameState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodedGameState { get; set; }
#nullable restore
#else
        public string CodedGameState { get; set; }
#endif
        /// <summary>The detailedState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetailedState { get; set; }
#nullable restore
#else
        public string DetailedState { get; set; }
#endif
        /// <summary>The startTimeTBD property</summary>
        public bool? StartTimeTBD { get; set; }
        /// <summary>The statusCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusCode { get; set; }
#nullable restore
#else
        public string StatusCode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.Game_gameData_status"/> and sets the default values.
        /// </summary>
        public Game_gameData_status()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.Game_gameData_status"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.Game_gameData_status CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.Game_gameData_status();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abstractGameState", n => { AbstractGameState = n.GetStringValue(); } },
                { "codedGameState", n => { CodedGameState = n.GetStringValue(); } },
                { "detailedState", n => { DetailedState = n.GetStringValue(); } },
                { "startTimeTBD", n => { StartTimeTBD = n.GetBoolValue(); } },
                { "statusCode", n => { StatusCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("abstractGameState", AbstractGameState);
            writer.WriteStringValue("codedGameState", CodedGameState);
            writer.WriteStringValue("detailedState", DetailedState);
            writer.WriteBoolValue("startTimeTBD", StartTimeTBD);
            writer.WriteStringValue("statusCode", StatusCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
