// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Game_liveData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The boxscore property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.GameBoxscore? Boxscore { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.GameBoxscore Boxscore { get; set; }
#endif
        /// <summary>The decisions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Game_liveData_decisions? Decisions { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Game_liveData_decisions Decisions { get; set; }
#endif
        /// <summary>The linescore property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.GameLinescore? Linescore { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.GameLinescore Linescore { get; set; }
#endif
        /// <summary>The plays property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Game_liveData_plays? Plays { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Game_liveData_plays Plays { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.Game_liveData"/> and sets the default values.
        /// </summary>
        public Game_liveData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.Game_liveData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.Game_liveData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.Game_liveData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "boxscore", n => { Boxscore = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.GameBoxscore>(global::DataHandler.NhlApiClient.Models.GameBoxscore.CreateFromDiscriminatorValue); } },
                { "decisions", n => { Decisions = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Game_liveData_decisions>(global::DataHandler.NhlApiClient.Models.Game_liveData_decisions.CreateFromDiscriminatorValue); } },
                { "linescore", n => { Linescore = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.GameLinescore>(global::DataHandler.NhlApiClient.Models.GameLinescore.CreateFromDiscriminatorValue); } },
                { "plays", n => { Plays = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Game_liveData_plays>(global::DataHandler.NhlApiClient.Models.Game_liveData_plays.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.GameBoxscore>("boxscore", Boxscore);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Game_liveData_decisions>("decisions", Decisions);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.GameLinescore>("linescore", Linescore);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Game_liveData_plays>("plays", Plays);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
