// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GameBoxscoreTeam_teamStats_teamSkaterStats : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The blocked property</summary>
        public double? Blocked { get; set; }
        /// <summary>The faceOffWinPercentage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FaceOffWinPercentage { get; set; }
#nullable restore
#else
        public string FaceOffWinPercentage { get; set; }
#endif
        /// <summary>The giveaways property</summary>
        public double? Giveaways { get; set; }
        /// <summary>The goals property</summary>
        public double? Goals { get; set; }
        /// <summary>The hits property</summary>
        public double? Hits { get; set; }
        /// <summary>The pim property</summary>
        public double? Pim { get; set; }
        /// <summary>The powerPlayGoals property</summary>
        public double? PowerPlayGoals { get; set; }
        /// <summary>The powerPlayOpportunities property</summary>
        public double? PowerPlayOpportunities { get; set; }
        /// <summary>The powerPlayPercentage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowerPlayPercentage { get; set; }
#nullable restore
#else
        public string PowerPlayPercentage { get; set; }
#endif
        /// <summary>The shots property</summary>
        public double? Shots { get; set; }
        /// <summary>The takeaways property</summary>
        public double? Takeaways { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.GameBoxscoreTeam_teamStats_teamSkaterStats"/> and sets the default values.
        /// </summary>
        public GameBoxscoreTeam_teamStats_teamSkaterStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.GameBoxscoreTeam_teamStats_teamSkaterStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.GameBoxscoreTeam_teamStats_teamSkaterStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.GameBoxscoreTeam_teamStats_teamSkaterStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blocked", n => { Blocked = n.GetDoubleValue(); } },
                { "faceOffWinPercentage", n => { FaceOffWinPercentage = n.GetStringValue(); } },
                { "giveaways", n => { Giveaways = n.GetDoubleValue(); } },
                { "goals", n => { Goals = n.GetDoubleValue(); } },
                { "hits", n => { Hits = n.GetDoubleValue(); } },
                { "pim", n => { Pim = n.GetDoubleValue(); } },
                { "powerPlayGoals", n => { PowerPlayGoals = n.GetDoubleValue(); } },
                { "powerPlayOpportunities", n => { PowerPlayOpportunities = n.GetDoubleValue(); } },
                { "powerPlayPercentage", n => { PowerPlayPercentage = n.GetStringValue(); } },
                { "shots", n => { Shots = n.GetDoubleValue(); } },
                { "takeaways", n => { Takeaways = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("blocked", Blocked);
            writer.WriteStringValue("faceOffWinPercentage", FaceOffWinPercentage);
            writer.WriteDoubleValue("giveaways", Giveaways);
            writer.WriteDoubleValue("goals", Goals);
            writer.WriteDoubleValue("hits", Hits);
            writer.WriteDoubleValue("pim", Pim);
            writer.WriteDoubleValue("powerPlayGoals", PowerPlayGoals);
            writer.WriteDoubleValue("powerPlayOpportunities", PowerPlayOpportunities);
            writer.WriteStringValue("powerPlayPercentage", PowerPlayPercentage);
            writer.WriteDoubleValue("shots", Shots);
            writer.WriteDoubleValue("takeaways", Takeaways);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
