// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GameLinescoreTeam : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The goaliePulled property</summary>
        public bool? GoaliePulled { get; set; }
        /// <summary>The goals property</summary>
        public double? Goals { get; set; }
        /// <summary>The numSkaters property</summary>
        public double? NumSkaters { get; set; }
        /// <summary>The powerPlay property</summary>
        public bool? PowerPlay { get; set; }
        /// <summary>The shotsOnGoal property</summary>
        public double? ShotsOnGoal { get; set; }
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.GameLinescoreTeam_team? Team { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.GameLinescoreTeam_team Team { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.GameLinescoreTeam"/> and sets the default values.
        /// </summary>
        public GameLinescoreTeam()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.GameLinescoreTeam"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.GameLinescoreTeam CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.GameLinescoreTeam();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "goaliePulled", n => { GoaliePulled = n.GetBoolValue(); } },
                { "goals", n => { Goals = n.GetDoubleValue(); } },
                { "numSkaters", n => { NumSkaters = n.GetDoubleValue(); } },
                { "powerPlay", n => { PowerPlay = n.GetBoolValue(); } },
                { "shotsOnGoal", n => { ShotsOnGoal = n.GetDoubleValue(); } },
                { "team", n => { Team = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.GameLinescoreTeam_team>(global::DataHandler.NhlApiClient.Models.GameLinescoreTeam_team.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("goaliePulled", GoaliePulled);
            writer.WriteDoubleValue("goals", Goals);
            writer.WriteDoubleValue("numSkaters", NumSkaters);
            writer.WriteBoolValue("powerPlay", PowerPlay);
            writer.WriteDoubleValue("shotsOnGoal", ShotsOnGoal);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.GameLinescoreTeam_team>("team", Team);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
