// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GameEditorial_tokenData_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "hyperLink")]
        #pragma warning disable CS1591
        HyperLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "playerCard")]
        #pragma warning disable CS1591
        PlayerCard,
        #pragma warning restore CS1591
    }
}
