// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GameOfficial_officialType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Linesman")]
        #pragma warning disable CS1591
        Linesman,
        #pragma warning restore CS1591
        [EnumMember(Value = "Referee")]
        #pragma warning disable CS1591
        Referee,
        #pragma warning restore CS1591
    }
}
