// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GameEditorialKeyword_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "bodyParagraphCount")]
        #pragma warning disable CS1591
        BodyParagraphCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "bodyWordCount")]
        #pragma warning disable CS1591
        BodyWordCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "clob_autoTagSkip_playerCards")]
        #pragma warning disable CS1591
        Clob_autoTagSkip_playerCards,
        #pragma warning restore CS1591
        [EnumMember(Value = "content")]
        #pragma warning disable CS1591
        Content,
        #pragma warning restore CS1591
        [EnumMember(Value = "embeddable")]
        #pragma warning disable CS1591
        Embeddable,
        #pragma warning restore CS1591
        [EnumMember(Value = "gameId")]
        #pragma warning disable CS1591
        GameId,
        #pragma warning restore CS1591
        [EnumMember(Value = "language")]
        #pragma warning disable CS1591
        Language,
        #pragma warning restore CS1591
        [EnumMember(Value = "playerId")]
        #pragma warning disable CS1591
        PlayerId,
        #pragma warning restore CS1591
        [EnumMember(Value = "previewParagraphCount")]
        #pragma warning disable CS1591
        PreviewParagraphCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "primaryTag")]
        #pragma warning disable CS1591
        PrimaryTag,
        #pragma warning restore CS1591
        [EnumMember(Value = "previewWordCount")]
        #pragma warning disable CS1591
        PreviewWordCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "shareable")]
        #pragma warning disable CS1591
        Shareable,
        #pragma warning restore CS1591
        [EnumMember(Value = "statsEventId")]
        #pragma warning disable CS1591
        StatsEventId,
        #pragma warning restore CS1591
        [EnumMember(Value = "teamFileCode")]
        #pragma warning disable CS1591
        TeamFileCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "teamId")]
        #pragma warning disable CS1591
        TeamId,
        #pragma warning restore CS1591
    }
}
