// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GameHighlight_playbacks_name
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FLASH_192K_320X180")]
        #pragma warning disable CS1591
        FLASH_192K_320X180,
        #pragma warning restore CS1591
        [EnumMember(Value = "FLASH_450K_400X224")]
        #pragma warning disable CS1591
        FLASH_450K_400X224,
        #pragma warning restore CS1591
        [EnumMember(Value = "FLASH_1200K_640X360")]
        #pragma warning disable CS1591
        FLASH_1200K_640X360,
        #pragma warning restore CS1591
        [EnumMember(Value = "FLASH_1800K_960X540")]
        #pragma warning disable CS1591
        FLASH_1800K_960X540,
        #pragma warning restore CS1591
        [EnumMember(Value = "HTTP_CLOUD_MOBILE")]
        #pragma warning disable CS1591
        HTTP_CLOUD_MOBILE,
        #pragma warning restore CS1591
        [EnumMember(Value = "HTTP_CLOUD_TABLET")]
        #pragma warning disable CS1591
        HTTP_CLOUD_TABLET,
        #pragma warning restore CS1591
        [EnumMember(Value = "HTTP_CLOUD_TABLET_60")]
        #pragma warning disable CS1591
        HTTP_CLOUD_TABLET_60,
        #pragma warning restore CS1591
        [EnumMember(Value = "HTTP_CLOUD_WIRED")]
        #pragma warning disable CS1591
        HTTP_CLOUD_WIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "HTTP_CLOUD_WIRED_60")]
        #pragma warning disable CS1591
        HTTP_CLOUD_WIRED_60,
        #pragma warning restore CS1591
        [EnumMember(Value = "HTTP_CLOUD_WIRED_WEB")]
        #pragma warning disable CS1591
        HTTP_CLOUD_WIRED_WEB,
        #pragma warning restore CS1591
    }
}
