// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlayerStatsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The gameLog property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.DetailedGameLog>? GameLog { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.DetailedGameLog> GameLog { get; set; }
#endif
        /// <summary>The gameTypeId property</summary>
        public int? GameTypeId { get; set; }
        /// <summary>The playerStatsSeasons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.PlayerStatsSeason>? PlayerStatsSeasons { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.PlayerStatsSeason> PlayerStatsSeasons { get; set; }
#endif
        /// <summary>The seasonId property</summary>
        public int? SeasonId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.PlayerStatsResponse"/> and sets the default values.
        /// </summary>
        public PlayerStatsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.PlayerStatsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.PlayerStatsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.PlayerStatsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gameLog", n => { GameLog = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.DetailedGameLog>(global::DataHandler.NhlApiClient.Models.DetailedGameLog.CreateFromDiscriminatorValue)?.AsList(); } },
                { "gameTypeId", n => { GameTypeId = n.GetIntValue(); } },
                { "playerStatsSeasons", n => { PlayerStatsSeasons = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.PlayerStatsSeason>(global::DataHandler.NhlApiClient.Models.PlayerStatsSeason.CreateFromDiscriminatorValue)?.AsList(); } },
                { "seasonId", n => { SeasonId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.DetailedGameLog>("gameLog", GameLog);
            writer.WriteIntValue("gameTypeId", GameTypeId);
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.PlayerStatsSeason>("playerStatsSeasons", PlayerStatsSeasons);
            writer.WriteIntValue("seasonId", SeasonId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
