// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlayerResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The awards property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.Award>? Awards { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.Award> Awards { get; set; }
#endif
        /// <summary>The badges property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.Badge>? Badges { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.Badge> Badges { get; set; }
#endif
        /// <summary>The birthCity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? BirthCity { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText BirthCity { get; set; }
#endif
        /// <summary>The birthCountry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BirthCountry { get; set; }
#nullable restore
#else
        public string BirthCountry { get; set; }
#endif
        /// <summary>The birthDate property</summary>
        public Date? BirthDate { get; set; }
        /// <summary>The birthStateProvince property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? BirthStateProvince { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText BirthStateProvince { get; set; }
#endif
        /// <summary>The careerTotals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.CareerTotals? CareerTotals { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.CareerTotals CareerTotals { get; set; }
#endif
        /// <summary>The currentTeamAbbrev property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentTeamAbbrev { get; set; }
#nullable restore
#else
        public string CurrentTeamAbbrev { get; set; }
#endif
        /// <summary>The currentTeamId property</summary>
        public int? CurrentTeamId { get; set; }
        /// <summary>The currentTeamRoster property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.PlayerSummary>? CurrentTeamRoster { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.PlayerSummary> CurrentTeamRoster { get; set; }
#endif
        /// <summary>The draftDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.DraftDetails? DraftDetails { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.DraftDetails DraftDetails { get; set; }
#endif
        /// <summary>The featuredStats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.FeaturedStats? FeaturedStats { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.FeaturedStats FeaturedStats { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? FirstName { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText FirstName { get; set; }
#endif
        /// <summary>The fullTeamName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? FullTeamName { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText FullTeamName { get; set; }
#endif
        /// <summary>The headshot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Headshot { get; set; }
#nullable restore
#else
        public string Headshot { get; set; }
#endif
        /// <summary>The heightInCentimeters property</summary>
        public int? HeightInCentimeters { get; set; }
        /// <summary>The heightInInches property</summary>
        public int? HeightInInches { get; set; }
        /// <summary>The heroImage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeroImage { get; set; }
#nullable restore
#else
        public string HeroImage { get; set; }
#endif
        /// <summary>The inHHOF property</summary>
        public int? InHHOF { get; set; }
        /// <summary>The inTop100AllTime property</summary>
        public int? InTop100AllTime { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The last5Games property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.GameStats>? Last5Games { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.GameStats> Last5Games { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? LastName { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText LastName { get; set; }
#endif
        /// <summary>The playerId property</summary>
        public int? PlayerId { get; set; }
        /// <summary>The playerSlug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlayerSlug { get; set; }
#nullable restore
#else
        public string PlayerSlug { get; set; }
#endif
        /// <summary>The position property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Position { get; set; }
#nullable restore
#else
        public string Position { get; set; }
#endif
        /// <summary>The seasonTotals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.SeasonTotal>? SeasonTotals { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.SeasonTotal> SeasonTotals { get; set; }
#endif
        /// <summary>The shootsCatches property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShootsCatches { get; set; }
#nullable restore
#else
        public string ShootsCatches { get; set; }
#endif
        /// <summary>The sweaterNumber property</summary>
        public int? SweaterNumber { get; set; }
        /// <summary>The teamCommonName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? TeamCommonName { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText TeamCommonName { get; set; }
#endif
        /// <summary>The teamLogo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamLogo { get; set; }
#nullable restore
#else
        public string TeamLogo { get; set; }
#endif
        /// <summary>The teamPlaceNameWithPreposition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? TeamPlaceNameWithPreposition { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText TeamPlaceNameWithPreposition { get; set; }
#endif
        /// <summary>The weightInKilograms property</summary>
        public int? WeightInKilograms { get; set; }
        /// <summary>The weightInPounds property</summary>
        public int? WeightInPounds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.PlayerResponse"/> and sets the default values.
        /// </summary>
        public PlayerResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.PlayerResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.PlayerResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.PlayerResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "awards", n => { Awards = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Award>(global::DataHandler.NhlApiClient.Models.Award.CreateFromDiscriminatorValue)?.AsList(); } },
                { "badges", n => { Badges = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Badge>(global::DataHandler.NhlApiClient.Models.Badge.CreateFromDiscriminatorValue)?.AsList(); } },
                { "birthCity", n => { BirthCity = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "birthCountry", n => { BirthCountry = n.GetStringValue(); } },
                { "birthDate", n => { BirthDate = n.GetDateValue(); } },
                { "birthStateProvince", n => { BirthStateProvince = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "careerTotals", n => { CareerTotals = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.CareerTotals>(global::DataHandler.NhlApiClient.Models.CareerTotals.CreateFromDiscriminatorValue); } },
                { "currentTeamAbbrev", n => { CurrentTeamAbbrev = n.GetStringValue(); } },
                { "currentTeamId", n => { CurrentTeamId = n.GetIntValue(); } },
                { "currentTeamRoster", n => { CurrentTeamRoster = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.PlayerSummary>(global::DataHandler.NhlApiClient.Models.PlayerSummary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "draftDetails", n => { DraftDetails = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.DraftDetails>(global::DataHandler.NhlApiClient.Models.DraftDetails.CreateFromDiscriminatorValue); } },
                { "featuredStats", n => { FeaturedStats = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.FeaturedStats>(global::DataHandler.NhlApiClient.Models.FeaturedStats.CreateFromDiscriminatorValue); } },
                { "firstName", n => { FirstName = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "fullTeamName", n => { FullTeamName = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "headshot", n => { Headshot = n.GetStringValue(); } },
                { "heightInCentimeters", n => { HeightInCentimeters = n.GetIntValue(); } },
                { "heightInInches", n => { HeightInInches = n.GetIntValue(); } },
                { "heroImage", n => { HeroImage = n.GetStringValue(); } },
                { "inHHOF", n => { InHHOF = n.GetIntValue(); } },
                { "inTop100AllTime", n => { InTop100AllTime = n.GetIntValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "last5Games", n => { Last5Games = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.GameStats>(global::DataHandler.NhlApiClient.Models.GameStats.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastName", n => { LastName = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "playerId", n => { PlayerId = n.GetIntValue(); } },
                { "playerSlug", n => { PlayerSlug = n.GetStringValue(); } },
                { "position", n => { Position = n.GetStringValue(); } },
                { "seasonTotals", n => { SeasonTotals = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.SeasonTotal>(global::DataHandler.NhlApiClient.Models.SeasonTotal.CreateFromDiscriminatorValue)?.AsList(); } },
                { "shootsCatches", n => { ShootsCatches = n.GetStringValue(); } },
                { "sweaterNumber", n => { SweaterNumber = n.GetIntValue(); } },
                { "teamCommonName", n => { TeamCommonName = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "teamLogo", n => { TeamLogo = n.GetStringValue(); } },
                { "teamPlaceNameWithPreposition", n => { TeamPlaceNameWithPreposition = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "weightInKilograms", n => { WeightInKilograms = n.GetIntValue(); } },
                { "weightInPounds", n => { WeightInPounds = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Award>("awards", Awards);
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Badge>("badges", Badges);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("birthCity", BirthCity);
            writer.WriteStringValue("birthCountry", BirthCountry);
            writer.WriteDateValue("birthDate", BirthDate);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("birthStateProvince", BirthStateProvince);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.CareerTotals>("careerTotals", CareerTotals);
            writer.WriteStringValue("currentTeamAbbrev", CurrentTeamAbbrev);
            writer.WriteIntValue("currentTeamId", CurrentTeamId);
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.PlayerSummary>("currentTeamRoster", CurrentTeamRoster);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.DraftDetails>("draftDetails", DraftDetails);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.FeaturedStats>("featuredStats", FeaturedStats);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("firstName", FirstName);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("fullTeamName", FullTeamName);
            writer.WriteStringValue("headshot", Headshot);
            writer.WriteIntValue("heightInCentimeters", HeightInCentimeters);
            writer.WriteIntValue("heightInInches", HeightInInches);
            writer.WriteStringValue("heroImage", HeroImage);
            writer.WriteIntValue("inHHOF", InHHOF);
            writer.WriteIntValue("inTop100AllTime", InTop100AllTime);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.GameStats>("last5Games", Last5Games);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("lastName", LastName);
            writer.WriteIntValue("playerId", PlayerId);
            writer.WriteStringValue("playerSlug", PlayerSlug);
            writer.WriteStringValue("position", Position);
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.SeasonTotal>("seasonTotals", SeasonTotals);
            writer.WriteStringValue("shootsCatches", ShootsCatches);
            writer.WriteIntValue("sweaterNumber", SweaterNumber);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("teamCommonName", TeamCommonName);
            writer.WriteStringValue("teamLogo", TeamLogo);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("teamPlaceNameWithPreposition", TeamPlaceNameWithPreposition);
            writer.WriteIntValue("weightInKilograms", WeightInKilograms);
            writer.WriteIntValue("weightInPounds", WeightInPounds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
