// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Player_shootsCatches
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "L")]
        #pragma warning disable CS1591
        L,
        #pragma warning restore CS1591
        [EnumMember(Value = "R")]
        #pragma warning disable CS1591
        R,
        #pragma warning restore CS1591
    }
}
