// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Player : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alternateCaptain property</summary>
        public bool? AlternateCaptain { get; set; }
        /// <summary>The birthCity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BirthCity { get; set; }
#nullable restore
#else
        public string BirthCity { get; set; }
#endif
        /// <summary>The birthCountry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BirthCountry { get; set; }
#nullable restore
#else
        public string BirthCountry { get; set; }
#endif
        /// <summary>The birthDate property</summary>
        public Date? BirthDate { get; set; }
        /// <summary>The birthStateProvince property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BirthStateProvince { get; set; }
#nullable restore
#else
        public string BirthStateProvince { get; set; }
#endif
        /// <summary>The captain property</summary>
        public bool? Captain { get; set; }
        /// <summary>The currentAge property</summary>
        public double? CurrentAge { get; set; }
        /// <summary>The currentTeam property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Player_currentTeam? CurrentTeam { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Player_currentTeam CurrentTeam { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The fullName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullName { get; set; }
#nullable restore
#else
        public string FullName { get; set; }
#endif
        /// <summary>The height property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Height { get; set; }
#nullable restore
#else
        public string Height { get; set; }
#endif
        /// <summary>The id property</summary>
        public double? Id { get; set; }
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The link property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Link { get; set; }
#nullable restore
#else
        public string Link { get; set; }
#endif
        /// <summary>The nationality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nationality { get; set; }
#nullable restore
#else
        public string Nationality { get; set; }
#endif
        /// <summary>The primaryNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryNumber { get; set; }
#nullable restore
#else
        public string PrimaryNumber { get; set; }
#endif
        /// <summary>The primaryPosition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.Player_primaryPosition? PrimaryPosition { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.Player_primaryPosition PrimaryPosition { get; set; }
#endif
        /// <summary>The rookie property</summary>
        public bool? Rookie { get; set; }
        /// <summary>The rosterStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RosterStatus { get; set; }
#nullable restore
#else
        public string RosterStatus { get; set; }
#endif
        /// <summary>The shootsCatches property</summary>
        public global::DataHandler.NhlApiClient.Models.Player_shootsCatches? ShootsCatches { get; set; }
        /// <summary>The weight property</summary>
        public double? Weight { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.Player"/> and sets the default values.
        /// </summary>
        public Player()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.Player"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.Player CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.Player();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "alternateCaptain", n => { AlternateCaptain = n.GetBoolValue(); } },
                { "birthCity", n => { BirthCity = n.GetStringValue(); } },
                { "birthCountry", n => { BirthCountry = n.GetStringValue(); } },
                { "birthDate", n => { BirthDate = n.GetDateValue(); } },
                { "birthStateProvince", n => { BirthStateProvince = n.GetStringValue(); } },
                { "captain", n => { Captain = n.GetBoolValue(); } },
                { "currentAge", n => { CurrentAge = n.GetDoubleValue(); } },
                { "currentTeam", n => { CurrentTeam = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Player_currentTeam>(global::DataHandler.NhlApiClient.Models.Player_currentTeam.CreateFromDiscriminatorValue); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "fullName", n => { FullName = n.GetStringValue(); } },
                { "height", n => { Height = n.GetStringValue(); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "link", n => { Link = n.GetStringValue(); } },
                { "nationality", n => { Nationality = n.GetStringValue(); } },
                { "primaryNumber", n => { PrimaryNumber = n.GetStringValue(); } },
                { "primaryPosition", n => { PrimaryPosition = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.Player_primaryPosition>(global::DataHandler.NhlApiClient.Models.Player_primaryPosition.CreateFromDiscriminatorValue); } },
                { "rookie", n => { Rookie = n.GetBoolValue(); } },
                { "rosterStatus", n => { RosterStatus = n.GetStringValue(); } },
                { "shootsCatches", n => { ShootsCatches = n.GetEnumValue<global::DataHandler.NhlApiClient.Models.Player_shootsCatches>(); } },
                { "weight", n => { Weight = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteBoolValue("alternateCaptain", AlternateCaptain);
            writer.WriteStringValue("birthCity", BirthCity);
            writer.WriteStringValue("birthCountry", BirthCountry);
            writer.WriteDateValue("birthDate", BirthDate);
            writer.WriteStringValue("birthStateProvince", BirthStateProvince);
            writer.WriteBoolValue("captain", Captain);
            writer.WriteDoubleValue("currentAge", CurrentAge);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Player_currentTeam>("currentTeam", CurrentTeam);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("fullName", FullName);
            writer.WriteStringValue("height", Height);
            writer.WriteDoubleValue("id", Id);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteStringValue("link", Link);
            writer.WriteStringValue("nationality", Nationality);
            writer.WriteStringValue("primaryNumber", PrimaryNumber);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.Player_primaryPosition>("primaryPosition", PrimaryPosition);
            writer.WriteBoolValue("rookie", Rookie);
            writer.WriteStringValue("rosterStatus", RosterStatus);
            writer.WriteEnumValue<global::DataHandler.NhlApiClient.Models.Player_shootsCatches>("shootsCatches", ShootsCatches);
            writer.WriteDoubleValue("weight", Weight);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
