// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ScheduleGame_tickets_ticketType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "buysell")]
        #pragma warning disable CS1591
        Buysell,
        #pragma warning restore CS1591
        [EnumMember(Value = "club buysell")]
        #pragma warning disable CS1591
        ClubBuysell,
        #pragma warning restore CS1591
        [EnumMember(Value = "club mobile")]
        #pragma warning disable CS1591
        ClubMobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "club mobile buysell")]
        #pragma warning disable CS1591
        ClubMobileBuysell,
        #pragma warning restore CS1591
        [EnumMember(Value = "club ticket")]
        #pragma warning disable CS1591
        ClubTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobile app ticket")]
        #pragma warning disable CS1591
        MobileAppTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobile buysell")]
        #pragma warning disable CS1591
        MobileBuysell,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobile ticket")]
        #pragma warning disable CS1591
        MobileTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "tablet app ticket")]
        #pragma warning disable CS1591
        TabletAppTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "ticket")]
        #pragma warning disable CS1591
        Ticket,
        #pragma warning restore CS1591
    }
}
