// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Standings_records_standingsType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "regularSeason")]
        #pragma warning disable CS1591
        RegularSeason,
        #pragma warning restore CS1591
    }
}
