// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatLeader : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? FirstName { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText FirstName { get; set; }
#endif
        /// <summary>The headshot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Headshot { get; set; }
#nullable restore
#else
        public string Headshot { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? LastName { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText LastName { get; set; }
#endif
        /// <summary>The position property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Position { get; set; }
#nullable restore
#else
        public string Position { get; set; }
#endif
        /// <summary>The sweaterNumber property</summary>
        public int? SweaterNumber { get; set; }
        /// <summary>The teamAbbrev property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamAbbrev { get; set; }
#nullable restore
#else
        public string TeamAbbrev { get; set; }
#endif
        /// <summary>The teamLogo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamLogo { get; set; }
#nullable restore
#else
        public string TeamLogo { get; set; }
#endif
        /// <summary>The teamName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DataHandler.NhlApiClient.Models.LocalizedText? TeamName { get; set; }
#nullable restore
#else
        public global::DataHandler.NhlApiClient.Models.LocalizedText TeamName { get; set; }
#endif
        /// <summary>The value property</summary>
        public int? Value { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.StatLeader"/> and sets the default values.
        /// </summary>
        public StatLeader()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.StatLeader"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.StatLeader CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.StatLeader();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "firstName", n => { FirstName = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "headshot", n => { Headshot = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "lastName", n => { LastName = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetStringValue(); } },
                { "sweaterNumber", n => { SweaterNumber = n.GetIntValue(); } },
                { "teamAbbrev", n => { TeamAbbrev = n.GetStringValue(); } },
                { "teamLogo", n => { TeamLogo = n.GetStringValue(); } },
                { "teamName", n => { TeamName = n.GetObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>(global::DataHandler.NhlApiClient.Models.LocalizedText.CreateFromDiscriminatorValue); } },
                { "value", n => { Value = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("firstName", FirstName);
            writer.WriteStringValue("headshot", Headshot);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("lastName", LastName);
            writer.WriteStringValue("position", Position);
            writer.WriteIntValue("sweaterNumber", SweaterNumber);
            writer.WriteStringValue("teamAbbrev", TeamAbbrev);
            writer.WriteStringValue("teamLogo", TeamLogo);
            writer.WriteObjectValue<global::DataHandler.NhlApiClient.Models.LocalizedText>("teamName", TeamName);
            writer.WriteIntValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
