// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Team_nextGameSchedule : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule_dates>? Dates { get; set; }
#nullable restore
#else
        public List<global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule_dates> Dates { get; set; }
#endif
        /// <summary>The totalEvents property</summary>
        public double? TotalEvents { get; set; }
        /// <summary>The totalGames property</summary>
        public double? TotalGames { get; set; }
        /// <summary>The totalItems property</summary>
        public double? TotalItems { get; set; }
        /// <summary>The totalMatches property</summary>
        public double? TotalMatches { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule"/> and sets the default values.
        /// </summary>
        public Team_nextGameSchedule()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dates", n => { Dates = n.GetCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule_dates>(global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule_dates.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalEvents", n => { TotalEvents = n.GetDoubleValue(); } },
                { "totalGames", n => { TotalGames = n.GetDoubleValue(); } },
                { "totalItems", n => { TotalItems = n.GetDoubleValue(); } },
                { "totalMatches", n => { TotalMatches = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DataHandler.NhlApiClient.Models.Team_nextGameSchedule_dates>("dates", Dates);
            writer.WriteDoubleValue("totalEvents", TotalEvents);
            writer.WriteDoubleValue("totalGames", TotalGames);
            writer.WriteDoubleValue("totalItems", TotalItems);
            writer.WriteDoubleValue("totalMatches", TotalMatches);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
