// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Team_nextGameSchedule_dates_games_status_statusCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "2")]
        #pragma warning disable CS1591
        Two,
        #pragma warning restore CS1591
        [EnumMember(Value = "3")]
        #pragma warning disable CS1591
        Three,
        #pragma warning restore CS1591
    }
}
