// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DataHandler.NhlApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Team_nextGameSchedule_dates_games_status_abstractGameState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
        [EnumMember(Value = "Preview")]
        #pragma warning disable CS1591
        Preview,
        #pragma warning restore CS1591
    }
}
