// <auto-generated/>
#pragma warning disable CS0618
using DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current;
using DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DataHandler.NhlApiClient.V1.SkaterStatsLeaders
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\skater-stats-leaders
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SkaterStatsLeadersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The current property</summary>
        public global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder Current
        {
            get => new global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Current.CurrentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the DataHandler.NhlApiClient.v1.skaterStatsLeaders.item collection</summary>
        /// <param name="position">Season in YYYYYYYY format, where the first four digits represent the start year of the season, and the last four digits represent the end year.</param>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Item.WithSeasonItemRequestBuilder"/></returns>
        public global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Item.WithSeasonItemRequestBuilder this[double position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("season", position);
                return new global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Item.WithSeasonItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the DataHandler.NhlApiClient.v1.skaterStatsLeaders.item collection</summary>
        /// <param name="position">Season in YYYYYYYY format, where the first four digits represent the start year of the season, and the last four digits represent the end year.</param>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Item.WithSeasonItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Item.WithSeasonItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("season", position);
                return new global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.Item.WithSeasonItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.SkaterStatsLeadersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SkaterStatsLeadersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/skater-stats-leaders", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.SkaterStatsLeadersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SkaterStatsLeadersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/skater-stats-leaders", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
