// <auto-generated/>
#pragma warning disable CS0618
using DataHandler.NhlApiClient.V1.Network;
using DataHandler.NhlApiClient.V1.Player;
using DataHandler.NhlApiClient.V1.Season;
using DataHandler.NhlApiClient.V1.SkaterStatsLeaders;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DataHandler.NhlApiClient.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The network property</summary>
        public global::DataHandler.NhlApiClient.V1.Network.NetworkRequestBuilder Network
        {
            get => new global::DataHandler.NhlApiClient.V1.Network.NetworkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The player property</summary>
        public global::DataHandler.NhlApiClient.V1.Player.PlayerRequestBuilder Player
        {
            get => new global::DataHandler.NhlApiClient.V1.Player.PlayerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The season property</summary>
        public global::DataHandler.NhlApiClient.V1.Season.SeasonRequestBuilder Season
        {
            get => new global::DataHandler.NhlApiClient.V1.Season.SeasonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The skaterStatsLeaders property</summary>
        public global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.SkaterStatsLeadersRequestBuilder SkaterStatsLeaders
        {
            get => new global::DataHandler.NhlApiClient.V1.SkaterStatsLeaders.SkaterStatsLeadersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
