// <auto-generated/>
#pragma warning disable CS0618
using DataHandler.NhlApiClient.V1.Player.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DataHandler.NhlApiClient.V1.Player
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\player
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlayerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the DataHandler.NhlApiClient.v1.player.item collection</summary>
        /// <param name="position">The player ID</param>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.V1.Player.Item.WithPlayerItemRequestBuilder"/></returns>
        public global::DataHandler.NhlApiClient.V1.Player.Item.WithPlayerItemRequestBuilder this[double position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("player", position);
                return new global::DataHandler.NhlApiClient.V1.Player.Item.WithPlayerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the DataHandler.NhlApiClient.v1.player.item collection</summary>
        /// <param name="position">The player ID</param>
        /// <returns>A <see cref="global::DataHandler.NhlApiClient.V1.Player.Item.WithPlayerItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::DataHandler.NhlApiClient.V1.Player.Item.WithPlayerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("player", position);
                return new global::DataHandler.NhlApiClient.V1.Player.Item.WithPlayerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.Player.PlayerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/player", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DataHandler.NhlApiClient.V1.Player.PlayerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/player", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
